### ISSUE TITLE
Can we disable the replacement for KeyboardError with non alphabet?

### ISSUE THREAD

**Issue by sidoqi** [makcedward/nlpaug#55]
Hi @makcedward,

I have purpose to augment the string to with some keyboard error. However, i don't want the characters replaced by non alphabets (e.g: punctuation). Is it possible to disable it? thanks

**Comment by makcedward** [comment]
Will enhance in coming release. 

Before that you may modify internal variable to achieve it 
```
text = "testing"
aug = KeyboardAug()
aug.model.include_spec=False
aug.augment(text)
```

**Comment by sidoqi** [comment]
Ok then, thanks man!

**Comment by hadyan-tvlk** [comment]
@makcedward after test it, i still found the augmenter replace it with number or some symbols (e.g: *, %, @).

Is there other workaround for this one? Thanks!

**Comment by sidoqi** [comment]
@makcedward after test it, i still found the augmenter replace it with number or some symbols (e.g: *, %, @). Is there other workaround for this one? Thanks!

The reason why i need for all the non-alphabets to be removed from the replacement candidates is because i want to mimic the misspelled in the phone keyboard instead desktop keyboard. Maybe we can specific keyboard object like `MobileKeyboardAug`?

**Comment by makcedward** [comment]
It is fixed and ready for git's master branch. Next version will include this fix and it will be released soon. You may reinstall it before formal release by:
`pip install git+https://github.com/makcedward/nlpaug.git`

**Comment by sidoqi** [comment]
@makcedward Already upgrade it to the latest (`v0.0.9`), however still found cases where the non-alphabets like number and punctuation still exist.

**Comment by makcedward** [comment]
@emesha92 
Thanks for reminder. Just published 0.0.10. Please try again. Here is the sample code

```
import nlpaug.augmenter.char as nac
aug = nac.KeyboardAug(special_char=False, numeric=False, upper_case=False)
for i in range(10):
    print(aug.augment('qwertyuiopklmzxasd'))
```

**Comment by sidoqi** [comment]
Thanks @makcedward, now it's working like a charm
